; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27043.0 

	TITLE	A:\12_수업사전소스\모비스장기과정\DAY7\square.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?square@@YAHH@Z					; square
; Function compile flags: /Odtp
; File a:\12_수업사전소스\모비스장기과정\day7\square.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
?square@@YAHH@Z PROC					; square

; 4    : {

	push	ebp
	mov	ebp, esp

; 5    : 	return a * a;

	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]

; 6    : }

	pop	ebp
	ret	0
?square@@YAHH@Z ENDP					; square
_TEXT	ENDS
END
